"""update user

Revision ID: 93296f283ff3
Revises: e750d36f7a5f
Create Date: 2026-01-05 17:42:40.054035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93296f283ff3'
down_revision = 'e750d36f7a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_id', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credential_id')

    # ### end Alembic commands ###
