"""user update

Revision ID: e750d36f7a5f
Revises: 427a1651cac5
Create Date: 2026-01-04 21:35:22.375073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e750d36f7a5f'
down_revision = '427a1651cac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_public_key', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('current_sign_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_sign_count')
        batch_op.drop_column('credential_public_key')

    # ### end Alembic commands ###
