name: ICS


services:

  logingateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: logingateway
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db.ziti:5432/app
      SECRET_KEY: ${SECRET_KEY_GATEWAY}
      PYTHONPATH: /app/logingateway
    ports:
      - "5000:5000"

