location /_auth {
    internal;
    proxy_pass https://logingateway.ziti:5000/auth;

    proxy_set_header Cookie $http_cookie;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /_login {
    internal;
    return 302 /login_?next=$request_uri;
}

location ~ /(login_|userlogin) {
    proxy_pass https://logingateway.ziti:5000;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
}
