[plc]
plc1 ansible_host=192.168.69.2
plc2 ansible_host=192.168.69.3

[arm]
arm1 ansible_host=192.168.69.4 plc="2" plc_ziti="1"
arm2 ansible_host=192.168.69.5 plc="3" plc_ziti="2"

[conveyor]
conveyor1 ansible_host=192.168.69.6 plc="2" plc_ziti="1"
conveyor2 ansible_host=192.168.69.8 plc="3" plc_ziti="2"

[scada]
scada1 ansible_host=192.168.69.9

[tunneler]
plc1_tunneler ansible_host=192.168.69.2 identity="plc1_tunneler" plc_ziti="1" type="host"
plc2_tunneler ansible_host=192.168.69.3 identity="plc2_tunneler" plc_ziti="2" type="host"
conveyor1_tunneler ansible_host=192.168.69.6 identity="conveyor1_tunneler" plc_ziti="1" type="client"
conveyor2_tunneler ansible_host=192.168.69.8  identity="conveyor2_tunneler" plc_ziti="2" type="client"
arm1_tunneler ansible_host=192.168.69.4 identity="arm1_tunneler" plc_ziti="1" type="client"
arm2_tunneler ansible_host=192.168.69.5 identity="arm2_tunneler" plc_ziti="2" type="client"
scada_tunneler ansible_host=192.168.69.9 identity="scada_tunneler" type="scada"
db_tunneler ansible_host=192.168.69.11 identity="db_tunneler"
userhandler_tunneler ansible_host=192.168.69.12 identity="userhandler_tunneler"
login_gateway_tunneler ansible_host=192.168.69.13 identity="logingateway_tunneler"

[ziti:children]
tunneler

[ziti]
controller ansible_host=192.168.69.7
router ansible_host=192.168.69.10

[webauthn]
db ansible_host=192.168.69.11
userhandler ansible_host=192.168.69.12
logingateway ansible_host=192.168.69.


[all:vars]
ansible_user=aces
ansible_python_interpreter=/usr/bin/python3