services:


  db_user_handler:
    image: postgres:18.1
    volumes:
      - db_user_handler:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: app
    ports:
      - "5432:5432"

volumes:
  db_user_handler: null