name: ICS


services:

  db_user_handler:
    image: postgres:18.1
    container_name: db_user_handler
    depends_on:
      ziti-tunneler-db:
        condition: service_healthy
    volumes:
      - db_user_handler:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: app
    network_mode: service:ziti-tunneler-db

  user_handler:
    build:
      context: .
      dockerfile: webauth/userhandler/Dockerfile
    container_name: user_handler
    depends_on:
      ziti-tunneler-userhandler:
        condition: service_healthy
    volumes:
      - ./webauth/userhandler/app/migrations:/app/userhandler/app/migrations
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@ziti.db:5432/app
      SECRET_KEY: ${SECRET_KEY_USERHANDLER}
      ADMIN_INIT_TOKEN: ${ADMIN_INIT_TOKEN}
      PYTHONPATH: /app/userhandler
    network_mode: service:ziti-tunneler-userhandler

  ziti-tunneler-db:
    image: ${ZITI_ROUTER_IMAGE:-openziti/ziti-router:1.6.12}
    container_name: ziti-tunneler-db
    depends_on:
      ziti-tunneler-db-init:
        condition: service_completed_successfully
    volumes:
      - ziti-db:/ziti-router
      - ./ziti/enroll.sh:/ziti-router/enroll.sh
    environment:
      ZITI_CTRL_ADVERTISED_ADDRESS: ${ZITI_CTRL_ADVERTISED_ADDRESS:-}
      ZITI_CTRL_ADVERTISED_PORT: ${ZITI_CTRL_ADVERTISED_PORT:-}
      ZITI_ROUTER_ADVERTISED_ADDRESS: ${ZITI_ROUTER_ADVERTISED_ADDRESS:-ziti-tunneler-db}
      ZITI_ROUTER_PORT: ${ZITI_ROUTER_PORT:-3022}
      ZITI_ROUTER_MODE: ${ZITI_ROUTER_MODE:-host}
      ZITI_BOOTSTRAP: true
      ZITI_BOOTSTRAP_CONFIG: true
      ZITI_BOOTSTRAP_ENROLLMENT: true
      ZITI_AUTO_RENEW_CERTS: true
      ZITI_ROUTER_TYPE: ${ZITI_ROUTER_TYPE:-edge}
      ZITI_BOOTSTRAP_CONFIG_ARGS: null
    networks:
      - ziti
    command: run config.yml
    entrypoint:
      - /ziti-router/enroll.sh
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - ziti
        - agent
        - stats
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 15s
    user: ${ZIGGY_UID:-2171}

  ziti-tunneler-db-init:
    image: openziti/ziti-cli:1.6.12 
    container_name: ziti-tunneler-db-init
    depends_on:
      ziti-controller:
        condition: service_healthy
    volumes:
      - ziti-db:/ziti-router
      - ./webauth/userhandler/bootstrap_tunneler_db.sh:/bootstrap.sh
    environment:
      - ZITI_USER=${ZITI_USER:-admin}
      - ZITI_PWD=${ZITI_PWD}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-}
    networks:
      - ziti
    entrypoint:
      - /bin/sh
      - /bootstrap.sh

  ziti-tunneler-userhandler:
    image: ${ZITI_ROUTER_IMAGE:-openziti/ziti-router:1.6.12}
    container_name: ziti-tunneler-userhandler
    depends_on:
      ziti-tunneler-userhandler-init:
        condition: service_completed_successfully
    volumes:
      - ziti-userhandler:/ziti-router
      - ./ziti/enroll.sh:/ziti-router/enroll.sh
    environment:
      ZITI_CTRL_ADVERTISED_ADDRESS: ${ZITI_CTRL_ADVERTISED_ADDRESS:-}
      ZITI_CTRL_ADVERTISED_PORT: ${ZITI_CTRL_ADVERTISED_PORT:-}
      ZITI_ROUTER_ADVERTISED_ADDRESS: ${ZITI_ROUTER_ADVERTISED_ADDRESS:-ziti-tunneler-userhandler}
      ZITI_ROUTER_PORT: ${ZITI_ROUTER_PORT:-3022}
      ZITI_ROUTER_MODE: ${ZITI_ROUTER_MODE:-tproxy}
      ZITI_AUTO_RENEW_CERTS: true
      ZITI_ROUTER_TYPE: ${ZITI_ROUTER_TYPE:-edge}
    ports:
      - target: 5000
        published: 5000
        host_ip: 127.0.0.1 
    networks:
      - ziti
    command: run config.yml
    entrypoint:
      - /ziti-router/enroll.sh
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - ziti
        - agent
        - stats
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 15s
    user: root
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1

  ziti-tunneler-userhandler-init:
    image: openziti/ziti-cli:1.6.12
    container_name: ziti-tunneler-userhandler-init
    depends_on:
      ziti-controller:
        condition: service_healthy
    volumes:
      - ziti-userhandler:/ziti-router
      - ./webauth/userhandler/bootstrap_tunneler_userhandler.sh:/bootstrap.sh
    environment:
      - ZITI_USER=${ZITI_USER:-admin}
      - ZITI_PWD=${ZITI_PWD}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-}
    networks:
      - ziti
    entrypoint:
      - /bin/sh
      - /bootstrap.sh
    user: root


volumes:
  db_user_handler: null
  ziti-userhandler: null
  ziti-db: null
