name: pipeline

on:
    workflow_dispatch:

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello world"

    # lint-python:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - run: 
