name: pipeline

on:
    push: {}

jobs:

    lint-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v6
          - name: actionlint
            run: docker run --rm -v "$(pwd)":/repo --workdir /repo rhysd/actionlint:latest -color

    lint-python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            - name: Setup python
              uses: actions/setup-python@v6
              with:
                python-version: 3
            - name: Install flake8
              run: |
                python -m pip install --upgrade pip
                python -m pip install flake8
            - name: Run flake8
              run: flake8 --exclude ./webauth/userhandler/app/migrations/  .

    lint-docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: Hadolint
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
            recursive: true

    lint-docker-compose:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: dclint
          run: find . -type f -name "docker-compose.*" -exec docker run -t --rm -v "${PWD}:/app" zavoloklom/dclint {} \;

    lint-shell:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: shellcheck
          run: find . -type f -name "*.sh" -exec shellcheck {} \;

    lint-html:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: Setup node
          uses: actions/setup-node@v6
        - name: Install dependecies
          run: sudo apt-get update && sudo apt-get install -y jq
        - name: htmlhint
          run: |
            yarn add --dev htmlhint
            npx htmlhint --init
            jq '. + {"doctype-first": false}' .htmlhintrc > tmp && mv tmp .htmlhintrc
            npx htmlhint "**/*.html"

    test-network:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: Run containers
          run: |
            cp .env.example .env;
            docker compose up --build -d
        - name: Test plcs
          run: |
            all_healthy=false
            until [[ $all_healthy == true ]];
            do
                sleep 2
                plc1_status=$(docker inspect -f '{{.State.Status}}' plc1)
                plc2_status=$(docker inspect -f '{{.State.Status}}' plc2)
                plc3_status=$(docker inspect -f '{{.State.Status}}' plc3)
                plc4_status=$(docker inspect -f '{{.State.Status}}' plc4)

                if [[ "$plc1_status" == "exited" || "$plc1_status" == "dead" ]]; then
                  echo "plc1 error"
                  exit 1
                fi
                if [[ "$plc2_status" == "exited" || "$plc2_status" == "dead" ]]; then
                  echo "plc2 error"
                  exit 1
                fi
                if [[ "$plc3_status" == "exited" || "$plc3_status" == "dead" ]]; then
                  echo "plc3 error"
                  exit 1
                fi
                if [[ "$plc4_status" == "exited" || "$plc4_status" == "dead" ]]; then
                  echo "plc4 error"
                  exit 1
                fi

                if [[ "$(docker inspect -f '{{.State.Health.Status}}' plc1)" == "healthy" \
                    && "$(docker inspect -f '{{.State.Health.Status}}' plc2)" == "healthy" \
                    && "$(docker inspect -f '{{.State.Health.Status}}' plc3)" == "healthy" \
                    && "$(docker inspect -f '{{.State.Health.Status}}' plc4)" == "healthy" ]]; then
                  all_healthy=true
                fi
            done
        - name: Test hils
          run: |
            sleep 5

            docker logs hil1 | grep -q Waiting
            docker logs hil2 | grep -q Waiting
            docker logs hil3 | grep -q Waiting
            docker logs hil4 | grep -q Waiting

        - name: Test nginx and logingateway
          run: |
            sleep 10;
            if [[ 302 != $(curl -w "%{http_code}" -o /dev/null -s "http://localhost:5050/plc1/") ]]; then
              exit 1
            fi

        - name: Test scada
          run: |
            sleep 5
            docker logs scada | grep -q "import done!"

        - name: Test userhandler
          run: |
            sleep 5;

            if [[ 200 != $(docker exec user_handler curl -o /dev/null -s -w "%{http_code}" "http://localhost:5000") ]]; then
              exit 1
            fi
        